name: marvelheroes_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter_modular: ^5.0.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.19.0
  shared_preferences: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: ComicNeue
      fonts: 
        - asset: assets/fonts/ComicNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/ComicNeue-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/ComicNeue-Italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/ComicNeue-Light.ttf
          weight: 300
        - asset: assets/fonts/ComicNeue-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/ComicNeue-Regular.ttf